### ISSUE TITLE
Alternatives with "rank => -100" cause error

### ISSUE THREAD

**Issue by latk** [jeffreykegler/Marpa--R3#42]
The documentation for the "rank" adverb states:

> The range allowed for `rank` is implementation-defined, but numbers in the range between -134,217,727 and 134,217,727 will always be allowed. `rank` is 0 by default.

In reality, ranks < -1 will die.

Code to reproduce:

``` perl
use Marpa::R3 4.001_050;
Marpa::R3::Scanless::G->new({ source => \q{E ::= 'x' rank => -2} });
```

Error message:

```
wrap_g_rule_rank_set(): No error
stack traceback:
        [C]: in method 'rule_rank_set'
        ../kollos/kollos.lua:2633: in function <../kollos/kollos.lua:2542>
        (...tail calls...)
Marpa::R3 exception at bug.pl line 2.
```

This is a regression from Marpa::R2, where negative ranks do work as expected.

**Comment by jeffreykegler** [comment]
Fixed as of this commit.  If you can confirm that this is the fix, I'll close this issue.
