### ISSUE TITLE
Build from source fails: file cpan/engine/read_only.time-stamp missing

### ISSUE THREAD

**Issue by latk** [jeffreykegler/Marpa--R3#45]
When Marpa::R3 is installed from Git, the Makefile fails:

``` console
$ make
cd engine && make
make[1]: Entering directory '$MARPA_R3/cpan/engine'
make[1]: *** No rule to make target 'read_only.time-stamp', needed by 'gnu_ac_build.time-stamp'.  Stop.
make[1]: Leaving directory '$MARPA_R3/cpan/engine'
Makefile:1390: recipe for target 'engine/gnu_ac_build/.libs/libmarpa.a' failed
make: *** [engine/gnu_ac_build/.libs/libmarpa.a] Error 2
```

In the tarball uploaded to CPAN, a file `cpan/engine/read_only.time-stamp` is present. Should this file be checked in, or should the Makefile contain a rule to generate this file?

Workaround: `date >cpan/engine/read_only.time-stamp`

This error could have been detected with an automated build, e.g. via Travis CI. Would there be interest in a pull request to add the necessary config?

**Comment by jeffreykegler** [comment]
If you'd like to submit a pull request for the workaround, I'll look at it.  I'd want to be sure it does not break my development builds.

Re Travis Cl, I'd like to involve others in the discussion, so I'm asking about it on IRC.
