### ISSUE TITLE
slr.reversed_g1_escape is not declared during ambiguous parse

### ISSUE THREAD

**Issue by ghost** [jeffreykegler/Marpa--R3#48]
I get the following internal error when attempting an ambiguous parse:

`$ perl ./test.pl`
`...l/5.28.1/x86_64-linux-thread-multi/Marpa/R3/ASF2.pm:1419:6: member slr.reversed_g1_escape is not declared`
`stack traceback:`
`        [C]: in function 'error'`
`        ../kollos/kollos.lua:130: in metamethod '__index'`
`        ...l/5.28.1/x86_64-linux-thread-multi/Marpa/R3/ASF2.pm:1419:6: in main chunk`
`Marpa::R3 exception at ./test.pl line 31.`

Here's the shortest I could get my test code to duplicate the bug. Note that the MMM... and zzz... input strings appear minimal length to trigger the bug.

use Marpa::R3;
my $dsl = <<~ 'END_OF_SOURCE';
  :default ::= action => [ name, value]
  lexeme default = action => [ name, value]

  A ::= B+
  B ::= D | I | C
  D ::= 'D' V
  I ::= 'I' Ds E
  E ::= 'E' C
  E ::= 'E'
  Ds ::= D+
  V ~  N n
  n ~ [^n]
  N ~ [^\n]+
  C ~ '#' N n

  :discard ~ w
  w ~ [\s]+
  END_OF_SOURCE

my $input = <<'EOI';
I
D MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
E # zzzzzzz
D X
EOI

my $grammar = Marpa::R3::Grammar->new({source => \$dsl} );
$grammar->parse( \$input, {trace_terminals=>0});

**Comment by jeffreykegler** [comment]
Thanks for the test code.  I have been able to duplicate the bug.

**Comment by jeffreykegler** [comment]
I hope to find a fix over the next few days.

**Comment by jeffreykegler** [comment]
Fixed and added to the test suite in the two commits above referencing this issue.

**Comment by jeffreykegler** [comment]
Fix in CPAN release Marpa-R3-4.001_053
